# Generated by Django 3.2 on 2022-04-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0002_alter_furniture_dimensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
