# Generated by Django 3.2 on 2022-04-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0004_alter_furniture_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='furniture',
            old_name='Production',
            new_name='production',
        ),
    ]
