# Generated by Django 3.2 on 2022-04-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0005_rename_production_furniture_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='condition',
            field=models.CharField(blank=True, choices=[('Like New', 'Like New'), ('Good', 'Good'), ('Worn', 'Worn')], max_length=300, null=True),
        ),
    ]
