# Generated by Django 3.2 on 2022-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0007_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='get_friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
