# Generated by Django 3.2 on 2022-04-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0008_category_get_friendly_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='get_friendly_name',
        ),
    ]
